grid_dimensions:
- name: population
  type: float
- name: soil
  type: int
- name: culture
  type: vector
- name: technology
  type: int
- name: politics
  type: int
- name: prestige
  type: float

demographics:
  # yearly natural growth coefficient
  natural_growth: 0.1

geographics:
  # threshold of blue level (in RGB format) for sea characterization
  sea_blue_cutoff: 100
  # list of soil types
  soil_types:
  - forest
  - mediterranean
  # soil fertility depending on technology level
  fertility_per_technology_level:
    default:
      # forest fertility coefficient - green level in RGB multiplied by this value to get agricultural output from forest soils
      forest_fertility: 10
      # mediterranean fertily coefficient - orange level in RGB multiplied by this value to get agricultural output from mediterranean soils
      mediterranean_fertility: 5
    paleolithic:
      forest_fertility: 0.1
      mediterranean_fertility: 0.1
    neolithic:
      forest_fertility: 1
      mediterranean_fertility: 5
    copper_age:
      forest_fertility: 2
      mediterranean_fertility: 10
    bronze_age:
      forest_fertility: 5
      mediterranean_fertility: 20
    iron_age_1:
      forest_fertility: 40
      mediterranean_fertility: 30
    iron_age_2:
      forest_fertility: 60
      mediterranean_fertility: 40
    pre_industrial:
      forest_fertility: 100
      mediterranean_fertility: 80

scenarios:
  # population initialization for Neolithic scenario
  neolithic:
    # forest population initialization
    forest_population_initialization: 0.1
    # mediterranean population initialization
    mediterranean_population_initialization: 0.1
    # coordinates of neolithic start
    neolithic_start:
      x: 10
      y: 20

culture:
  # the cultural prestige is the product of :
  # - the tech level
  # - the political stage
  cultural_prestige_tech_coefficient: 1
  political_stage_coefficient: 1

technology:
  # each year, probability to reach next level is the product of :
  # - population
  # - political stage
  # - cultural surface beyond a given threshold
  # - contagion from neighbors
  tech_progress_population_coefficient: 1
  tech_progress_political_coefficient: 1
  tech_progress_cultural_coefficient: 1
  tech_progress_contagion_coefficient: 1

  # list of technological stages
  technological_stages:
  - paleolithic
  - neolithic
  - copper_age
  - iron_age_1
  - iron_age_2
  - pre_industrial

politics:
# list of the political stages
# each stage has
# - name
# - coef for cultural power
# - coef for tech progress
# - coef for tech adoption from neighbors
- name: barbarians
  culture_coefficient: 1
  tech_coefficient: 1
  tech_contagion_coefficient: 1
- name: feodal_1
  culture_coefficient: 1
  tech_coefficient: 1
  tech_contagion_coefficient: 1
- name: feodal_2
  culture_coefficient: 1
  tech_coefficient: 1
  tech_contagion_coefficient: 1
- name: feodal_3
  culture_coefficient: 1
  tech_coefficient: 1
  tech_contagion_coefficient: 1
- name: civil_wars
  culture_coefficient: 1
  tech_coefficient: 1
  tech_contagion_coefficient: 1

politics_progress:
  politics_progress_population_coefficient: 1
  politics_progress_contagion_coefficient: 1
